#!/usr/bin/env python3
"""Writes the Wave Plasma wording (fluid, extractor, interface, repeater, projector screen, Output
upgrade, JEI notes) into en_us.json and removes the old Totem Generator lines.

  python3 tools/gen_plasma_lang.py

Edit here and rerun.
"""
import json
from pathlib import Path

LANG = Path(__file__).resolve().parent.parent / "src/main/resources/assets/bsp_core/lang/en_us.json"

REMOVE_PREFIXES = ("gui.bsp_core.generator.", "tooltip.bsp_core.generator.", "message.bsp_core.generator.", "jei.bsp_core.info.generator", "block.bsp_core.totem_generator",
                   "item.bsp_core.reach_amplifier", "gui.bsp_core.projector.")
KEYS = {
    "fluid.bsp_core.wave_plasma": "Wave Plasma",
    "block.bsp_core.plasma_extractor": "Plasma Extractor",
    "block.bsp_core.plasma_interface": "Plasma Interface",
    "block.bsp_core.plasma_repeater": "Plasma Repeater",
    "block.bsp_core.totem_projector": "Projector",
    "block.bsp_core.tetrium_core_cable": "Tetrium Core Plasma Cable",
    "block.bsp_core.magnatite_core_cable": "Magnatite Core Plasma Cable",
    "block.bsp_core.illyrium_core_cable": "Illyrium Core Plasma Cable",
    "block.bsp_core.charged_illyrium_core_cable": "Charged Illyrium Core Plasma Cable",
    "item.bsp_core.channel_expander": "Channel Expander",
    "tooltip.bsp_core.channel_expander": "Right-click a Projector to fit it: the projector receives one more power",
    "buff.bsp_core.output": "Output",
    "buff.bsp_core.output.effect": "Gives off %s mB/t of Wave Plasma",
    "gui.bsp_core.projector.tab.powers": "POWERS",
    "gui.bsp_core.projector.tab.chunks": "CHUNKS",
    "gui.bsp_core.projector.tab.status": "STATUS",
    "gui.bsp_core.projector.col.power": "POWER",
    "gui.bsp_core.projector.col.offered": "OFFERED",
    "gui.bsp_core.projector.col.arrives": "ARRIVES",
    "gui.bsp_core.projector.receiving": "RECEIVING",
    "gui.bsp_core.projector.off": "off",
    "gui.bsp_core.projector.not_offered": "not offered",
    "gui.bsp_core.projector.channels": "Receiving %s of %s powers",
    "gui.bsp_core.projector.no_signal_help": "No interface is feeding this projector",
    "gui.bsp_core.projector.no_repeaters": "No repeaters in the run: powers arrive at full level",
    "gui.bsp_core.projector.repeaters": "%s repeater(s) in the run: one power at full level, or each one level lower per repeater",
    "gui.bsp_core.projector.lost": "Too weak to arrive past %s repeater(s). Receive it alone, or raise its level.",
    "gui.bsp_core.projector.active": "PROJECTING",
    "gui.bsp_core.projector.low_pressure": "LOW PRESSURE",
    "gui.bsp_core.projector.no_signal": "NO SIGNAL",
    "gui.bsp_core.projector.pressure": "PLASMA ARRIVING",
    "gui.bsp_core.projector.pressure_text": "%s of the %s mB/t needed",
    "gui.bsp_core.projector.tank": "Tank: %s / %s mB",
    "gui.bsp_core.projector.expander_fitted": "Channel Expander fitted",
    "gui.bsp_core.projector.expander_none": "No Channel Expander",
    "gui.bsp_core.projector.expander_help": "Right-click with one to fit it; sneak + right-click empty-handed to take it out.",
    "gui.bsp_core.projector.rule.0": "A repeater passes most of the pressure and starts a fresh cable run.",
    "gui.bsp_core.projector.rule.1": "Short of plasma? Raise the totem's Output or add a totem to the interface.",
    "gui.bsp_core.projector.rule.2": "Anchor received here lets you load chunks around this projector.",
    "gui.bsp_core.projector.rule.3": "Only the totem's owner can change what is received.",
    "gui.bsp_core.projector.chunks": "CHUNKS %s / %s",
    "gui.bsp_core.projector.chunks_off": "To load chunks from here, receive Anchor",
    "gui.bsp_core.projector.chunks_off2": "on the POWERS tab.",
    "gui.bsp_core.projector.chunks.hint": "Click chunks. The projector's own is always in.",
    "gui.bsp_core.projector.chunks.needs_power": "Needs a signal and plasma to hold chunks.",
    "gui.bsp_core.projector.chunks.not_owner": "Only the totem's owner can change this.",
    "gui.bsp_core.projector.chunks.shared": "From the totem's allowance. Range %1$s x %1$s",
    "message.bsp_core.projector.expander_fitted": "Channel Expander fitted",
    "message.bsp_core.projector.no_signal": "No signal: no Plasma Interface is feeding this projector",
    "message.bsp_core.projector.no_power": "Low pressure: %s mB/t of Wave Plasma must arrive for it to project",
    "message.bsp_core.projector.active": "Projecting: %s",
    "block.bsp_core.battery_charger": "Battery Charger",
    "block.bsp_core.plasma_battery_1": "Plasma Battery I",
    "block.bsp_core.plasma_battery_2": "Plasma Battery II",
    "block.bsp_core.plasma_battery_3": "Plasma Battery III",
    "block.bsp_core.plasma_battery_4": "Plasma Battery IV",
    "item.bsp_core.power_cell_1": "Power Cell I",
    "item.bsp_core.power_cell_2": "Power Cell II",
    "item.bsp_core.power_cell_3": "Power Cell III",
    "item.bsp_core.charged_resonance_crystal": "Charged Resonance Crystal",
    "tooltip.bsp_core.plasma.stored": "%s / %s mB Wave Plasma",
    "tooltip.bsp_core.plasma.no_powers": "Holds plasma only",
    "tooltip.bsp_core.plasma.power": "%s %s",
    "tooltip.bsp_core.plasma.powers": "%s of %s powers stamped",
    "tooltip.bsp_core.plasma.powers_empty": "No powers stamped yet (holds %2$s)",
    "gui.bsp_core.charger.filling": "FILLING",
    "gui.bsp_core.charger.fed": "FED, ITEM FULL",
    "gui.bsp_core.charger.no_signal": "NO SIGNAL",
    "gui.bsp_core.charger.tank": "Tank %s%% of %s mB",
    "gui.bsp_core.charger.arriving": "Arriving: %s mB/t",
    "gui.bsp_core.charger.empty": "Put a Plasma Battery or Power Cell in the slot.",
    "gui.bsp_core.charger.battery": "Battery: %s%% full",
    "gui.bsp_core.charger.cell": "Cell: %s%% full",
    "gui.bsp_core.charger.plasma_only": "This battery holds plasma only.",
    "gui.bsp_core.charger.stamps": "Stamped %s of %s powers",
    "gui.bsp_core.charger.col.power": "POWER",
    "gui.bsp_core.charger.col.offered": "OFFERED",
    "gui.bsp_core.charger.stamp": "stamp",
    "gui.bsp_core.charger.stamped": "STAMPED",
    "gui.bsp_core.charger.not_offered": "not offered",
    "gui.bsp_core.charger.not_owner": "Only the totem's owner can stamp.",
    "gui.bsp_core.charger.cell_note": "Cells take Carried powers; batteries take Base powers.",
    "need.bsp_core.nugget": "Magnatite Nuggets in the upgrade slot",
    "jei.bsp_core.centrifuge_magnetise_note": "A Resonance Crystal and one Magnatite Nugget from the upgrade slot",
    "jei.bsp_core.info.charger": "Plug a Plasma Cable into it and put a Plasma Battery or Power Cell in the slot. It fills the item with Wave Plasma and stamps powers the interface offers into it, chosen on its screen.",
    "jei.bsp_core.info.battery": "A tank of Wave Plasma that also holds stamped Base powers. Charge it in a Battery Charger, then stand it on a Plasma Extractor instead of a totem: it feeds the extractor at 100 mB/t with its powers until it runs dry. Higher tiers hold more plasma and more powers.",
    "jei.bsp_core.info.cell": "A small store of Wave Plasma with stamped Carried powers, charged in a Battery Charger. The Wave Emitter runs on it.",
    "jei.bsp_core.info.charged_crystal": "A Resonance Crystal magnetised in the Magnetic Centrifuge with a Magnatite Nugget. Every Plasma Battery and Power Cell is built around one.",
    "item.bsp_core.wave_emitter": "Wave Emitter",
    "tooltip.bsp_core.emitter.no_cell": "No Power Cell. Hold a cell in the other hand and right-click to fit it.",
    "tooltip.bsp_core.emitter.on": "ON: draws %s mB/t while in the offhand",
    "tooltip.bsp_core.emitter.off": "OFF (right-click to switch on; draws %s mB/t)",
    "tooltip.bsp_core.emitter.cell": "Cell: %s",
    "tooltip.bsp_core.emitter.hint": "Offhand. Right-click: on/off. Sneak + right-click: take the cell out.",
    "message.bsp_core.emitter.cell_in": "Power Cell fitted",
    "message.bsp_core.emitter.cell_out": "Power Cell taken out",
    "message.bsp_core.emitter.no_cell": "The emitter needs a Power Cell",
    "message.bsp_core.emitter.on": "Wave Emitter on",
    "message.bsp_core.emitter.off": "Wave Emitter off",
    "message.bsp_core.emitter.empty": "The Power Cell is empty: the Wave Emitter switched off",
    "jei.bsp_core.info.emitter": "Held in the offhand with a charged Power Cell fitted, it gives you the cell's Carried powers as the totem would, so the totem can stay safe at home. Right-click to switch it on; it draws 20 mB/t while on.",
    "item.bsp_core.raw_tetrium": "Raw Tetrium",
    "item.bsp_core.raw_illyrium": "Raw Illyrium",
    "item.bsp_core.raw_magnatite": "Raw Magnatite",
    "message.bsp_core.repeater.turned": "Repeater turned round",
    "config.jade.plugin_bsp_core.cable_flow": "Plasma cable flow",
    "jade.bsp_core.cable_flow": "Wave Plasma: %s mB/t",
    "jade.bsp_core.cable_idle": "No plasma flowing",
    "item.bsp_core.wrench": "Wrench",
    "tooltip.bsp_core.wrench": "Right-click a block to turn it: repeaters, totems, batteries, machines",
    "tooltip.bsp_core.wrench.sneak": "Sneak + right-click turns it the other way (a repeater turns round)",
    "jei.bsp_core.info.wrench": "Turns blocks in place without picking them up: a Plasma Repeater steps through its six directions (sneak to turn it round), a totem or machine turns a quarter, a battery swaps its axis.",
    "jei.bsp_core.info.extractor": "Place it directly under a placed Shatter Totem; more can stack below. It draws the totem's Wave Plasma out, split evenly between the stack. Any open face takes a Plasma Interface.",
    "jei.bsp_core.info.interface": "Touch it to a Plasma Extractor and plug Plasma Cables into it. Touching interfaces join into one, up to twelve blocks; more than that, or one touching a drum another interface already serves, shows a lit seam and does nothing.",
    "jei.bsp_core.info.repeater": "Put it in a cable run to start a fresh run. Plasma goes in through its dark back and out through its lit front; placed pointing the way you look, right-click with an empty hand turns it round. It passes most of the pressure, and a projector behind it receives one power at full level or several each a level lower per repeater.",
    "jei.bsp_core.info.expander": "Right-click a Projector with it: the projector then receives three powers at once instead of two.",
    "jei.bsp_core.info.projector": "Receives the powers a Plasma Interface offers and recreates them as a second aura. Needs 100 mB/t of Wave Plasma arriving. Right-click it to choose what it receives, pick chunks to load, and see its pressure.",
    "jei.bsp_core.info.cable": "Carries Wave Plasma from a Plasma Interface to Projectors at full pressure for its whole run: Tetrium Core 15 blocks, Magnatite Core 25, Illyrium Core 40, Charged Illyrium Core 80. A Plasma Repeater starts a fresh run.",
}

lang = json.loads(LANG.read_text())
lang = {k: v for k, v in lang.items() if not k.startswith(REMOVE_PREFIXES)}
lang.update(KEYS)
LANG.write_text(json.dumps(lang, indent=2, ensure_ascii=False) + "\n")
print(f"wrote {len(KEYS)} plasma lines")
