#!/usr/bin/env python3
"""Writes the Wave Plasma wording (fluid, extractor, interface, repeater, projector screen, Output
upgrade, JEI notes) into en_us.json and removes the old Totem Generator lines.

  python3 tools/gen_plasma_lang.py

Edit here and rerun.
"""
import json
from pathlib import Path

LANG = Path(__file__).resolve().parent.parent / "src/main/resources/assets/bsp_core/lang/en_us.json"

REMOVE_PREFIXES = ("gui.bsp_core.generator.", "tooltip.bsp_core.generator.", "message.bsp_core.generator.", "jei.bsp_core.info.generator", "block.bsp_core.totem_generator",
                   "item.bsp_core.reach_amplifier", "gui.bsp_core.projector.")
KEYS = {
    "fluid.bsp_core.wave_plasma": "Wave Plasma",
    "gui.bsp_core.shatter_totem.plasma": "Wave Plasma: %s mB/t (Output %s of %s)",
    "block.bsp_core.plasma_extractor": "Plasma Extractor",
    "block.bsp_core.plasma_interface": "Plasma Interface",
    "block.bsp_core.plasma_repeater": "Plasma Repeater",
    "block.bsp_core.plasma_valve": "Plasma Valve",
    "gui.bsp_core.valve.limit": "LIMIT, mB/t",
    "gui.bsp_core.valve.open": "OPEN",
    "gui.bsp_core.valve.shut_redstone": "SHUT BY REDSTONE",
    "gui.bsp_core.valve.shut_limit": "SHUT",
    "gui.bsp_core.valve.max": "MAX",
    "gui.bsp_core.valve.shut": "SHUT",
    "gui.bsp_core.valve.redstone_on": "REDSTONE: SHUTS IT",
    "gui.bsp_core.valve.redstone_off": "REDSTONE: IGNORED",
    "gui.bsp_core.valve.passing": "Offered %s mB/t, passing %s mB/t",
    "gui.bsp_core.valve.hint_redstone": "A lever on the valve or a redstone signal shuts it. Drag the dial or type a number.",
    "gui.bsp_core.valve.hint_free": "Redstone is ignored: only the limit sets the flow. Drag the dial or type a number.",
    "block.bsp_core.totem_projector": "Projector",
    "block.bsp_core.tetrium_core_cable": "Tetrium Plasma Cable",
    "block.bsp_core.magnatite_core_cable": "Magnatite Plasma Cable",
    "block.bsp_core.illyrium_core_cable": "Illyrium Plasma Cable",
    "block.bsp_core.charged_illyrium_core_cable": "Charged Illyrium Plasma Cable",
    "item.bsp_core.channel_expander": "Channel Expander",
    "tooltip.bsp_core.channel_expander": "Right-click a Projector to fit it: the projector receives one more power",
    "buff.bsp_core.output": "Output",
    "buff.bsp_core.output.effect": "Gives off %s mB/t of Wave Plasma",
    "gui.bsp_core.projector.tab.powers": "POWERS",
    "gui.bsp_core.projector.tab.chunks": "CHUNKS",
    "gui.bsp_core.projector.tab.status": "STATUS",
    "gui.bsp_core.projector.col.power": "POWER",
    "gui.bsp_core.projector.col.offered": "OFFERED",
    "gui.bsp_core.projector.col.arrives": "ARRIVES",
    "gui.bsp_core.projector.receiving": "RECEIVING",
    "gui.bsp_core.projector.off": "off",
    "gui.bsp_core.projector.not_offered": "not offered",
    "gui.bsp_core.projector.channels": "Receiving %s of %s powers",
    "gui.bsp_core.projector.no_signal_help": "No fed Projector Base under this projector",
    "gui.bsp_core.projector.no_repeaters": "No repeaters in the run: powers arrive at full level",
    "gui.bsp_core.projector.repeaters": "%s repeater(s) in the run: one power at full level, or each one level lower per repeater",
    "gui.bsp_core.projector.lost": "Too weak to arrive past %s repeater(s). Receive it alone, or raise its level.",
    "gui.bsp_core.projector.active": "PROJECTING",
    "gui.bsp_core.projector.low_pressure": "LOW PRESSURE",
    "gui.bsp_core.projector.no_signal": "NO SIGNAL",
    "gui.bsp_core.projector.pressure": "PLASMA ARRIVING",
    "gui.bsp_core.projector.pressure_text": "%s of the %s mB/t needed",
    "gui.bsp_core.projector.tank": "Tank: %s / %s mB",
    "gui.bsp_core.projector.expander_fitted": "Channel Expander fitted",
    "gui.bsp_core.projector.expander_none": "No Channel Expander",
    "gui.bsp_core.projector.expander_help": "Right-click with one to fit it; sneak + right-click empty-handed to take it out.",
    "gui.bsp_core.projector.rule.0": "A repeater passes most of the pressure and starts a fresh cable run.",
    "gui.bsp_core.projector.rule.1": "Short of plasma? Raise the totem's Output or add a totem to the interface.",
    "gui.bsp_core.projector.rule.2": "Anchor received here lets you load chunks around this projector.",
    "gui.bsp_core.projector.rule.3": "Only the totem's owner can change what is received.",
    "gui.bsp_core.projector.chunks": "CHUNKS %s / %s",
    "gui.bsp_core.projector.chunks_off": "To load chunks from here, receive Anchor",
    "gui.bsp_core.projector.chunks_off2": "on the POWERS tab.",
    "gui.bsp_core.projector.chunks.hint": "Click chunks. The projector's own is always in.",
    "gui.bsp_core.projector.chunks.needs_power": "Needs a signal and plasma to hold chunks.",
    "gui.bsp_core.projector.chunks.not_owner": "Only the totem's owner can change this.",
    "gui.bsp_core.projector.chunks.shared": "From the totem's allowance. Range %1$s x %1$s",
    "message.bsp_core.projector.expander_fitted": "Channel Expander fitted",
    "message.bsp_core.projector.no_signal": "No signal: the projector needs a Projector Base under it with a cable from a Plasma Interface",
    "message.bsp_core.projector.no_power": "Low pressure: %s mB/t of Wave Plasma must arrive for it to project",
    "message.bsp_core.projector.active": "Projecting: %s",
    "block.bsp_core.battery_charger": "Battery Charger",
    "block.bsp_core.plasma_battery_1": "Plasma Battery I",
    "block.bsp_core.plasma_battery_2": "Plasma Battery II",
    "block.bsp_core.plasma_battery_3": "Plasma Battery III",
    "block.bsp_core.plasma_battery_4": "Plasma Battery IV",
    "item.bsp_core.power_cell_1": "Power Cell I",
    "item.bsp_core.power_cell_2": "Power Cell II",
    "item.bsp_core.power_cell_3": "Power Cell III",
    "item.bsp_core.charged_resonance_crystal": "Charged Resonance Crystal",
    "tooltip.bsp_core.plasma.stored": "%s / %s mB Wave Plasma",
    "tooltip.bsp_core.plasma.no_powers": "Holds plasma only",
    "tooltip.bsp_core.plasma.power": "%s %s",
    "tooltip.bsp_core.plasma.powers": "%s of %s powers stamped",
    "tooltip.bsp_core.plasma.powers_empty": "No powers stamped yet (holds %2$s)",
    "gui.bsp_core.charger.filling": "FILLING",
    "gui.bsp_core.charger.fed": "FED, ITEM FULL",
    "gui.bsp_core.charger.no_signal": "NO SIGNAL",
    "gui.bsp_core.charger.tank": "Tank %s%% of %s mB",
    "gui.bsp_core.charger.arriving": "Arriving: %s mB/t",
    "gui.bsp_core.charger.empty": "Put a Plasma Battery or Power Cell in the slot.",
    "gui.bsp_core.charger.battery": "Battery: %s%% full",
    "gui.bsp_core.charger.cell": "Cell: %s%% full",
    "gui.bsp_core.charger.plasma_only": "This battery holds plasma only.",
    "gui.bsp_core.charger.stamps": "Stamped %s of %s powers",
    "gui.bsp_core.charger.col.power": "POWER",
    "gui.bsp_core.charger.col.offered": "OFFERED",
    "gui.bsp_core.charger.stamp": "stamp",
    "gui.bsp_core.charger.stamped": "STAMPED",
    "gui.bsp_core.charger.not_offered": "not offered",
    "gui.bsp_core.charger.not_owner": "Only the totem's owner can stamp.",
    "gui.bsp_core.charger.cell_note": "Cells take Carried powers; batteries take Base powers.",
    "need.bsp_core.nugget": "Magnatite Nuggets in the upgrade slot",
    "jei.bsp_core.centrifuge_magnetise_note": "A Resonance Crystal and one Magnatite Nugget from the upgrade slot",
    "jei.bsp_core.info.charger": "Placed with its open front toward you; the cable plugs into its back (the wrench turns it). Put a Plasma Battery or Power Cell in the slot. It fills the item with Wave Plasma and stamps powers the interface offers into it, chosen on its screen.",
    "jei.bsp_core.info.battery": "A tank of Wave Plasma that also holds stamped Base powers. Charge it in a Battery Charger, then stand it on a Plasma Extractor instead of a totem: it feeds the extractor at 100 mB/t with its powers until it runs dry. Higher tiers hold more plasma and more powers.",
    "jei.bsp_core.info.cell": "A small store of Wave Plasma with stamped Carried powers, charged in a Battery Charger. The Wave Emitter runs on it.",
    "jei.bsp_core.info.charged_crystal": "A Resonance Crystal magnetised in the Magnetic Centrifuge with a Magnatite Nugget. Every Plasma Battery and Power Cell is built around one.",
    "item.bsp_core.wave_emitter": "Wave Emitter",
    "tooltip.bsp_core.emitter.no_cell": "No Power Cell. Hold a cell in the other hand and right-click to fit it.",
    "tooltip.bsp_core.emitter.on": "ON: draws %s mB/t while in the offhand",
    "tooltip.bsp_core.emitter.off": "OFF (right-click to switch on; draws %s mB/t)",
    "tooltip.bsp_core.emitter.cell": "Cell: %s",
    "tooltip.bsp_core.emitter.hint": "Offhand. Right-click at the air to open it. At a block: on/off; sneak takes the cell out.",
    "guide.bsp_core.plasma.title": "Wave Plasma hook-up",
    "guide.bsp_core.plasma.step.0": "Start with a Plasma Extractor",
    "guide.bsp_core.plasma.tip.0": "The extractor draws plasma from the totem that stands on it. More extractors stacked below share the flow between them.",
    "guide.bsp_core.plasma.step.1": "Place your Shatter Totem on top",
    "guide.bsp_core.plasma.tip.1": "A placed totem gives 100 mB/t, up to 6,000 with the ten levels of the Output upgrade. Cloaking takes 50 of it while on.",
    "guide.bsp_core.plasma.step.2": "A Plasma Interface touching the extractor",
    "guide.bsp_core.plasma.tip.2": "Interfaces that touch join into one group of up to twelve. Cables plug into any outer face, and each face sends up to 1,000 mB/t, so a big totem needs a big group. Right-click it for the flow view.",
    "guide.bsp_core.plasma.step.3": "Plasma Cables from the interface",
    "guide.bsp_core.plasma.tip.3": "A run carries its full pressure to the end. Tetrium reaches 15 blocks and carries 250 mB/t, Magnatite 25 and 500, Illyrium 40 and 1,000, Charged Illyrium 80 and 1,000.",
    "guide.bsp_core.plasma.step.4": "A Plasma Valve in the run (optional)",
    "guide.bsp_core.plasma.tip.4": "Limits what passes it from its screen. A lever on it or a redstone signal shuts it. Powers pass unchanged.",
    "guide.bsp_core.plasma.step.5": "A Plasma Repeater (optional)",
    "guide.bsp_core.plasma.tip.5": "Starts a fresh run, plasma in through its dark back and out through its lit front. Costs a tenth of the pressure; the wrench turns it.",
    "guide.bsp_core.plasma.step.6": "A Projector Base at the end",
    "guide.bsp_core.plasma.tip.6": "Holds 5,000 mB. It needs 100 mB/t arriving to run a projector and burns 20 mB/t, so it keeps going for a while after a cut.",
    "guide.bsp_core.plasma.step.7": "The Projector on the base",
    "guide.bsp_core.plasma.tip.7": "Right-click it to choose the powers it receives. It runs on the plasma in its base: 100 mB/t arriving and it projects.",
    "guide.bsp_core.plasma.step.8": "A second run south",
    "guide.bsp_core.plasma.tip.8": "The interface shares its plasma equally between the runs leaving it. A run that needs less leaves the rest to the others.",
    "guide.bsp_core.plasma.step.9": "A Battery Charger, cable into its back",
    "guide.bsp_core.plasma.tip.9": "Fills the battery or cell standing in it and stamps powers into it. It only takes a cable at its back; place it facing you.",
    "block.bsp_core.tank_casing": "Tank Casing",
    "block.bsp_core.tank_glass": "Tank Glass",
    "block.bsp_core.tank_port": "Tank Port",
    "block.bsp_core.tetrium_glass": "Tetrium Glass",
    "gui.bsp_core.tank.title": "Plasma Tank",
    "gui.bsp_core.tank.of": "of %s mB (%s%%)",
    "gui.bsp_core.tank.size": "%s x %s x %s, %s blocks",
    "gui.bsp_core.tank.ports": "Ports: %s",
    "gui.bsp_core.tank.in": "In: %s mB/t",
    "gui.bsp_core.tank.out": "Out: %s mB/t",
    "gui.bsp_core.tank.help": "Drag to turn, right-drag to pan, scroll to zoom. Ports are labelled with their setting and what passes; the cables shown are the first three out of each port, not the whole network.",
    "gui.bsp_core.tank.unformed": "Not part of a tank",
    "gui.bsp_core.tank.unformed.help": "Build a hollow box of 3 to 12 blocks a side: Tank Casing on every edge, Tank Glass, Tank Casing or Tank Ports on the faces, nothing inside. It forms by itself when the last block goes in.",
    "gui.bsp_core.tank.mode.both": "In and out",
    "gui.bsp_core.tank.mode.input": "Input",
    "gui.bsp_core.tank.mode.output": "Output",
    "gui.bsp_core.tank.port.hint": "Right-click: next setting. Sneak + right-click: previous.",
    "message.bsp_core.tank.port": "Port: %s",
    "jade.bsp_core.tank_level": "Wave Plasma: %s / %s mB",
    "jade.bsp_core.tank_unformed": "Not part of a tank",
    "jade.bsp_core.tank_port": "%s: in %s, out %s mB/t",
    "jei.bsp_core.info.tank": "A hollow box of 3 to 12 blocks a side: Tank Casing on every edge, Tank Glass, Tank Casing or Tank Ports on the faces, nothing inside. It forms by itself and holds 5,000,000 mB of Wave Plasma per block of the shell, no powers. Ports take plasma from a run that comes from an interface and give it to runs that only lead to bases, chargers or other tanks; the wrench sets a port to Input or Output only. Right-click any block for the tank's screen. Break one block and the plasma waits for it to come back.",
    "jei.bsp_core.info.tetrium_glass": "Glass strengthened with Tetrium: the ingredient for Tank Glass.",
    "gui.bsp_core.emitter.cell": "POWER CELL",
    "gui.bsp_core.emitter.on": "ON",
    "gui.bsp_core.emitter.off": "OFF",
    "gui.bsp_core.emitter.state_running": "Running, %s mB/t",
    "gui.bsp_core.emitter.state_empty": "On, cell empty",
    "gui.bsp_core.emitter.state_off": "Off",
    "gui.bsp_core.emitter.state_no_cell": "No cell fitted",
    "gui.bsp_core.emitter.hint_cell": "Put a Power Cell in the slot.",
    "gui.bsp_core.emitter.hint_offhand": "The emitter works in your offhand.",
    "gui.bsp_core.emitter.stored": "%s / %s mB",
    "gui.bsp_core.emitter.time_left": "%s left at %s mB/t",
    "gui.bsp_core.emitter.time_none": "Empty: charge the cell",
    "gui.bsp_core.emitter.powers": "POWERS",
    "gui.bsp_core.emitter.power": "%s %s",
    "gui.bsp_core.emitter.no_powers": "None stamped",
    "gui.bsp_core.emitter.slots": "%s of %s",
    "message.bsp_core.emitter.cell_in": "Power Cell fitted",
    "message.bsp_core.emitter.cell_out": "Power Cell taken out",
    "message.bsp_core.emitter.no_cell": "The emitter needs a Power Cell",
    "message.bsp_core.emitter.on": "Wave Emitter on",
    "message.bsp_core.emitter.off": "Wave Emitter off",
    "message.bsp_core.emitter.empty": "The Power Cell is empty: the Wave Emitter switched off",
    "jei.bsp_core.info.emitter": "Held in the offhand with a charged Power Cell fitted, it gives you the cell's Carried powers as the totem would, so the totem can stay safe at home. Right-click at the air to open its screen: fit the cell, switch it on, see its powers and how long it will last. It draws 20 mB/t while on.",
    "item.bsp_core.raw_tetrium": "Raw Tetrium",
    "item.bsp_core.raw_illyrium": "Raw Illyrium",
    "item.bsp_core.raw_magnatite": "Raw Magnatite",
    "message.bsp_core.repeater.turned": "Repeater turned round",
    "config.jade.plugin_bsp_core.cable_flow": "Plasma cable flow",
    "jade.bsp_core.cable_flow": "Wave Plasma: %s mB/t",
    "jade.bsp_core.cable_idle": "No plasma flowing",
    "config.jade.plugin_bsp_core.plasma": "Plasma blocks",
    "jade.bsp_core.extractor_draw": "Drawing %s mB/t from the totem",
    "jade.bsp_core.extractor_idle": "No totem to draw from",
    "jade.bsp_core.base_tank": "Wave Plasma: %s / %s mB",
    "jade.bsp_core.valve_limit": "Letting through up to %s mB/t",
    "jade.bsp_core.valve_shut": "Shut (limit %s mB/t)",
    "item.bsp_core.wrench": "Wrench",
    "tooltip.bsp_core.wrench": "Right-click a block to turn it: repeaters, valves, totems, batteries, machines. On a cable it sets the end you point at.",
    "tooltip.bsp_core.wrench.sneak": "Sneak + right-click turns it the other way (a repeater turns round)",
    "jei.bsp_core.info.wrench": "Turns blocks in place without picking them up: a Plasma Repeater steps through its six directions (sneak to turn it round), a totem or machine turns a quarter, a battery swaps its axis.",
    "block.bsp_core.projector_base": "Projector Base",
    "gui.bsp_core.tree.auras.label": "AURAS",
    "jei.bsp_core.info.projector_base": "Plasma Cables plug into its four sides and it holds what arrives. Stand a Projector on it: the projector draws from the base. Cables do not join a projector directly.",
    "jei.bsp_core.info.extractor": "Place it directly under a placed Shatter Totem; more can stack below. It draws the totem's Wave Plasma out, split evenly between the stack. Any open face takes a Plasma Interface.",
    "jei.bsp_core.info.interface": "Hold Shift over any plasma block in JEI to see the whole hook-up built step by step. Touch it to a Plasma Extractor and plug Plasma Cables into it. Touching interfaces join into one, up to twelve blocks; more than that, or one touching an extractor another interface already serves, shows a lit seam and does nothing.",
    "jei.bsp_core.info.valve": "Put it in a cable run to limit what passes it, in mB/t, from its screen. A lever on it or a redstone signal shuts it, unless redstone control is switched off on the screen. Powers pass unchanged; it counts as one cable of reach and does not start a fresh run. The wrench turns its axis.",
    "jei.bsp_core.info.repeater": "Put it in a cable run to start a fresh run. Plasma goes in through its dark back and out through its lit front; placed pointing the way you look, right-click with an empty hand turns it round. It passes most of the pressure, and a projector behind it receives one power at full level or several each a level lower per repeater.",
    "jei.bsp_core.info.expander": "Right-click a Projector with it: the projector then receives three powers at once instead of two.",
    "jei.bsp_core.info.projector": "Stands on a Projector Base and receives the powers a Plasma Interface offers through it, recreating them as a second aura. Needs 100 mB/t of Wave Plasma arriving. Right-click it to choose what it receives, pick chunks to load, and see its pressure.",
    "jei.bsp_core.info.cable": "Carries Wave Plasma from a Plasma Interface to Projectors at full pressure for its whole run: Tetrium Core 15 blocks, Magnatite Core 25, Illyrium Core 40, Charged Illyrium Core 80. A Plasma Repeater starts a fresh run. Each kind also has a limit on what it carries: 250 mB/t for Tetrium, 500 for Magnatite, 1,000 for Illyrium and Charged Illyrium; a run is held to its weakest cable. Magnatite, Illyrium and Charged Illyrium cables can be dyed (eight round a dye): a coloured cable joins only its own colour and a plain one only plain ones, so runs can be kept apart. The wrench sets each end: Normal, Output, Input, Off, or Linked to another colour.",
}

# the dyed cables: "Blue Illyrium Plasma Cable" and so on, for every dye and every kind but Tetrium
for _kind, _kind_name in (("magnatite", "Magnatite"), ("illyrium", "Illyrium"), ("charged_illyrium", "Charged Illyrium")):
    for _dye in ("white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"):
        KEYS[f"block.bsp_core.{_dye}_{_kind}_core_cable"] = f"{_dye.replace('_', ' ').title()} {_kind_name} Plasma Cable"
KEYS.update({
    "gui.bsp_core.wrench.end.normal": "Normal",
    "gui.bsp_core.wrench.end.output": "Output",
    "gui.bsp_core.wrench.end.input": "Input",
    "gui.bsp_core.wrench.end.off": "Off",
    "gui.bsp_core.wrench.end.link": "Linked across colours",
    "gui.bsp_core.wrench.side.down": "Bottom",
    "gui.bsp_core.wrench.side.up": "Top",
    "gui.bsp_core.wrench.side.north": "North",
    "gui.bsp_core.wrench.side.south": "South",
    "gui.bsp_core.wrench.side.west": "West",
    "gui.bsp_core.wrench.side.east": "East",
    "message.bsp_core.wrench.end": "%s end: %s",
    "gui.bsp_core.wrench.core": "Core: sneak-click picks it up",
    "gui.bsp_core.wrench.core.hint": "Sneak + right-click: pick it up with its end settings",
    "gui.bsp_core.wrench.hint": "Right-click: next setting. Sneak + right-click: Normal.",
    "gui.bsp_core.wrench.hint.link": "Right-click: link it to the other colour",
    "jade.bsp_core.cable_ends": "Ends: %s",
    "tooltip.bsp_core.cable.ends": "Keeps its wrench-set ends when placed",
})

lang = json.loads(LANG.read_text())
lang = {k: v for k, v in lang.items() if not k.startswith(REMOVE_PREFIXES)}
lang.update(KEYS)
LANG.write_text(json.dumps(lang, indent=2, ensure_ascii=False) + "\n")
print(f"wrote {len(KEYS)} plasma lines")
